name: clip
description: .
version: 1.2.0
homepage: https://github.com/hsul4n/dart-clip

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  intl: ^0.18.0
  photo_view: ^0.14.0
  image_picker: ^0.8.7
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  test: ^1.24.0
