name: clip
description: .
version: 1.2.0
homepage: https://github.com/hsul4n/dart-clip

environment:
  sdk: ">=2.12.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  intl: ^0.18.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  test: ^1.25.14
